# Generated by Django 4.0.2 on 2022-02-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_name_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='someone', max_length=40),
        ),
    ]
