# Generated by Django 4.0.2 on 2022-02-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='fname',
            field=models.CharField(default='fsomeone', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='lname',
            field=models.CharField(default='lsomeone', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='textarea',
            field=models.CharField(default='msg', max_length=200),
        ),
    ]
